version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install packages
                # build the project into the dist directory
                command: npm install
            - run:
                name: Run tests
                # build the project into the dist directory
                command: npm run test
workflows:
  build-and-test:
    jobs:
      - build-and-test
