name: Auto Tag

on:
  push:
    branches: [ master ]

jobs:
  tag-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set latest tag on push to master
        run: .github/scripts/auto-tag.sh
